#!/bin/sh
LIBDIR=/data/lib
LIBS=
for JAR in $LIBDIR/*.jar
do
  LIBS=$LIBS:$JAR
done
exec scala -deprecation -cp $LIBS "$0" "$@"
!#

import ninthdrug.mail.Mail.mail

mail("contact@jobfilter.nl", "trungadinh@gmail.com", "testing", "testing")
