#!/bin/sh
LIBS=@CACHEDIR@
for JAR in @LIBDIR@/*.jar
do
  LIBS=$LIBS:$JAR
done
exec /opt/scala/bin/scala -cp $LIBS "$0" "$@"
!#

import ninthdrug.http._

val server = new WebServer(
  ServerConfig(
    "/data/ninthdrug/scriptcache",
    List(
      SiteConfig("www.jobfilter.nl", "95.211.101.208", 8080, "", "/data/websites/www.jobfilter.nl"),
      SiteConfig("www.do_it.nl", "95.211.101.208", 9090, "", "/data/websites/www.it-do.nl")
    )
  )
)

server.run()
