#!/bin/sh
LIBS=@CACHEDIR@
for JAR in @LIBDIR@/*.jar
do
  LIBS=$LIBS:$JAR
done
exec scala -cp $LIBS $0 $@
!#

import ninthdrug.http._

val server = new WebServer(
  ServerConfig(
    "@CACHEDIR@",
    List(
      SiteConfig("localhost", "", 8080, "", "/data/websites/localhost_8080"),
      SiteConfig("www.do_it.nl", "95.211.101.208", 9090, "", "/data/websites/www.it-do.nl")
    )
  )
)

server.run()
